// Package executequery is a Go-native port of upstream
// google/googlesql's execute_query tool, layered on top of
// go-googlesql (pure-Go GoogleSQL bindings via wazero).
//
// Today it supports the parse, unparse, and analyze tool modes; the
// unanalyze, explain, and execute modes are recognised at the CLI
// surface but return ErrUnsupportedMode because go-googlesql
// does not yet expose SQLBuilder or a reference evaluator. See
// AGENTS.md for the full feature matrix.
//
// Proto binding architecture
//
// go-googlesql exposes two kinds of generated Go types:
//
//   1. Handle types (e.g. LanguageOptions, AnalyzerOptions, ResolvedNode)
//      thin wrappers around a uint64 pointer to a C++ object living inside
//      the WASM runtime.
//   2. Message types (suffixed *Proto, e.g. LanguageOptionsProto)
//      wrappers around C++ google::protobuf::Message objects generated by
//      protoc-gen-cpp on the upstream side.
//
// Because the C++ side is compiled with protoc-gen-cpp output, every
// *Proto type carries the standard protobuf wire-format methods
// ParseFromString and SerializeToString (inherited from MessageLite).
// This means any *Proto value can be exchanged with an idiomatic
// protoc-gen-go struct built from the same .proto definition, simply
// by passing wire-format bytes through the WASM boundary.
//
// We already exploit this pattern in two places:
//
// 1. catalog/sample_proto.go — wire-format shunt for descriptors:
//
//	descriptorpb.FileDescriptorProto (protoc-gen-go)
//	      | proto.Marshal
//	      v
//	[]byte wire
//	      | ParseFromString(string(wire))
//	      v
//	googlesql.FileDescriptorProto (protoc-gen-wasmify-go)
//	      | pool.BuildFile(wfdp)
//	      v
//	*googlesql.FileDescriptor   (C++ object inside WASM)
//
// 2. enabledfeatures.go / enabledrewrites.go — protoreflect for
//    enum metadata.  go-googlesql does not expose enum-descriptor
//    iterators (no LanguageFeature_descriptor()->value_count()), so
//    zz_enums.go mirrors the enum tables by hand.  But the
//    *annotations* on each enum value (e.g. `in_development` options)
//    *are* available through the protoc-gen-go copy of options.proto:
//    File_googlesql_public_options_proto.Enums().ByName(...).
//    This lets us read proto extensions from the standard Go struct
//    and match them to go-googlesql enum values by name rather than
//    by numeric value (which would be fragile because the wasm
//    binding renumbers enums).
//
// What is blocked by missing Serialize/Deserialize
//
// The bridge only becomes useful when a Handle type exposes a method
// that converts to (or from) its matching *Proto type.  Many important
// handles lack this, which prevents us from using protoc-gen-go
// structs to drive the API:
//
//   Handle type           Missing method                Impact
//   --------------------  ----------------------------  ------------------------------------------
//   AnalyzerOptions       Deserialize(proto)            Cannot load analyzer settings from JSON/YAML/proto
//   ASTNode (parse tree)  Serialize(proto)              Cannot emit AST as JSON/textproto (--output_mode)
//   ResolvedNode          Serialize(proto)              Cannot emit resolved AST as JSON/textproto
//   Value (evaluator)     Serialize(valueProto)         Cannot emit execute results as JSON/textproto
//   PreparedQuery         (entire type not exported)    execute / explain modes are impossible
//
// If go-googlesql ever adds those methods, the missing features above
// could be implemented almost entirely with standard protoc-gen-go
// types plus the existing wire-format shunt, without any new wasm-side
// work.
package executequery
