#!/bin/sh
# Regenerate zz_enums.go from the linked go-googlesql source.
# Run from the repo root.
set -eu

src="$(go list -m -f '{{.Dir}}' github.com/goccy/go-googlesql)/googlesql.go"
if ! [ -f "$src" ]; then
  echo "cannot find go-googlesql source at $src" >&2
  exit 1
fi
ver="$(go list -m -f '{{.Version}}' github.com/goccy/go-googlesql)"

{
  echo "// Code generated by hack/gen-enums.sh from go-googlesql ${ver}; DO NOT EDIT."
  echo "//"
  echo "// Workaround [go-googlesql ${ver}]: there is no runtime accessor"
  echo "// that enumerates the LanguageFeature / ResolvedASTRewrite enum"
  echo "// values, so the FeatureSet / RewriteSet flag parsers cannot iterate"
  echo "// \"every known enum value\" without help."
  echo "//"
  echo "// Upstream C++ API: protobuf-generated enum descriptor accessors"
  echo "//   - googlesql::LanguageFeature_descriptor()->value_count() / value(i)"
  echo "//   - googlesql::ResolvedASTRewrite_descriptor()->value_count() / value(i)"
  echo "// declared by protoc-gen-cpp from the enum definitions in"
  echo "// third_party/googlesql/googlesql/public/options.proto"
  echo "// (enum LanguageFeature is at line 119; enum ResolvedASTRewrite"
  echo "// is in the same file)."
  echo "//"
  echo "// Natural Go code:"
  echo "//   for i := int32(0); i < googlesql.LanguageFeatureValuesCount(); i++ {"
  echo "//       f := googlesql.LanguageFeatureValue(i)"
  echo "//       ..."
  echo "//   }"
  echo "//"
  echo "// Instead, this generated file mirrors the enum tables out of"
  echo "// go-googlesql's source via hack/gen-enums.sh. Regenerate after"
  echo "// bumping the go-googlesql module version. Unblocked when"
  echo "// go-googlesql binds the protobuf enum-descriptor iterators (or"
  echo "// exports a curated \"all values\" slice)."
  echo "package executequery"
  echo ""
  echo "import googlesql \"github.com/goccy/go-googlesql\""
  echo ""
  echo "var allLanguageFeatures = []googlesql.LanguageFeature{"
  grep -E "^\tLanguageFeature[A-Za-z0-9]+ +LanguageFeature = " "$src" |
    sed -E 's/^\t(LanguageFeature[A-Za-z0-9]+) .*/	googlesql.\1,/'
  echo "}"
  echo ""
  echo "var allResolvedASTRewrites = []googlesql.ResolvedASTRewrite{"
  grep -E "^\tResolvedASTRewrite[A-Za-z0-9]+ +ResolvedASTRewrite = " "$src" |
    sed -E 's/^\t(ResolvedASTRewrite[A-Za-z0-9]+) .*/	googlesql.\1,/'
  echo "}"
} >zz_enums.go

gofmt -w zz_enums.go
