#!/bin/sh
# Regenerate zz_enums.go from the linked goccy/go-googlesql source.
# Run from the repo root.
set -eu

src="$(go list -m -f '{{.Dir}}' github.com/goccy/go-googlesql)/googlesql.go"
if ! [ -f "$src" ]; then
  echo "cannot find go-googlesql source at $src" >&2
  exit 1
fi
ver="$(go list -m -f '{{.Version}}' github.com/goccy/go-googlesql)"

{
  echo "// Code generated by hack/gen-enums.sh from go-googlesql ${ver}; DO NOT EDIT."
  echo "package executequery"
  echo ""
  echo "import googlesql \"github.com/goccy/go-googlesql\""
  echo ""
  echo "var allLanguageFeatures = []googlesql.LanguageFeature{"
  grep -E "^\tLanguageFeature[A-Za-z0-9]+ +LanguageFeature = " "$src" |
    sed -E 's/^\t(LanguageFeature[A-Za-z0-9]+) .*/	googlesql.\1,/'
  echo "}"
  echo ""
  echo "var allResolvedASTRewrites = []googlesql.ResolvedASTRewrite{"
  grep -E "^\tResolvedASTRewrite[A-Za-z0-9]+ +ResolvedASTRewrite = " "$src" |
    sed -E 's/^\t(ResolvedASTRewrite[A-Za-z0-9]+) .*/	googlesql.\1,/'
  echo "}"
} >zz_enums.go

gofmt -w zz_enums.go
